version: "3"

services:
  mongo-dev:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: wine_locals
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
    ports:
      - "27031:27017"
    volumes:
      - ./mongo-init-dev.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-test:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: wine_locals_test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
    ports:
      - "27030:27017"
    volumes:
      - ./mongo-init-test.js:/docker-entrypoint-initdb.d/mongo-init.js:ro